
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Calculus'
tagline:          'from http://cnx.org/contents/9a1df55a-b167-4736-b5ad-15d996704270@4.136 (CC-BY-NC-SA)'
url:              https://github.com/philschatz/calculus-book
origin:           http://cnx.org/contents/9a1df55a-b167-4736-b5ad-15d996704270@4.136

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          4.136

bookviewer:       http://philschatz.com/book-viewer

